version: '3.8'
services:
  proxy:
    image: nginx:alpine
    container_name: Rajesh_Portfolio_Proxy
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - web_bridge
    restart: unless-stopped

  web:
    container_name: Rajesh_Portfolio
    build:
      context: .
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-production}
    expose:
      - 3000
    networks:
      - web_bridge
    env_file:
      - .env
    restart: unless-stopped
networks:
  web_bridge:
    external: true