version: '3.8'
services:
  proxy:
    image: nginx:alpine
    container_name: Rajesh_Portfolio_Proxy
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - web_bridge
    restart: unless-stopped

  web:
    container_name: Rajesh_Portfolio
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    expose:
      - 3000
    networks:
      - web_bridge
    environment:
      - NODE_ENV=development
    command: npm run dev
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
networks:
  web_bridge:
    external: true