import * as React from 'react';
import {
  SiJavascript,
  SiTypescript,
  SiPython,
  SiPhp,
  SiOpenjdk,
  SiReact,
  SiNextdotjs,
  SiRedux,
  SiHtml5,
  SiCss3,
  SiSass,
  SiTailwindcss,
  SiBootstrap,
  SiMui,
  SiWebpack,
  SiNodedotjs,
  SiExpress,
  SiTerraform,
  SiDocker,
  SiGithubactions,
  SiGit,
  SiGooglecloud,
  SiMongodb,
  SiMysql,
  SiSqlite,
  SiSalesforce,
  SiMagento,
  SiWordpress,
  SiAdobe,
  SiAdobephotoshop,
  SiAdobexd,
  SiAdobeillustrator,
} from 'react-icons/si';
import { VscAzure } from 'react-icons/vsc';
import AccountTreeIcon from '@mui/icons-material/AccountTree';
import ApiIcon from '@mui/icons-material/Api';
// Each glyph carries its own brand colour; anything unmapped renders as a plain chip.
export const skillIcons: Record<string, React.ReactElement> = {
  javascript: <SiJavascript color="#f7df1e" />,
  typescript: <SiTypescript color="#3178c6" />,
  python: <SiPython color="#3776ab" />,
  php: <SiPhp color="#777bb4" />,
  java: <SiOpenjdk color="#ed8b00" />,
  react: <SiReact color="#61dafb" />,
  nextdotjs: <SiNextdotjs />,
  redux: <SiRedux color="#764abc" />,
  html5: <SiHtml5 color="#e34f26" />,
  css3: <SiCss3 color="#1572b6" />,
  sass: <SiSass color="#cc6699" />,
  tailwindcss: <SiTailwindcss color="#06b6d4" />,
  bootstrap: <SiBootstrap color="#7952b3" />,
  mui: <SiMui color="#007fff" />,
  webpack: <SiWebpack color="#8dd6f9" />,
  nodedotjs: <SiNodedotjs color="#339933" />,
  express: <SiExpress />,
  microservices: <AccountTreeIcon sx={{ fontSize: 'inherit' }} />,
  api: <ApiIcon sx={{ fontSize: 'inherit' }} />,
  azure: <VscAzure color="#0078d4" />,
  gcp: <SiGooglecloud color="#4285f4" />,
  terraform: <SiTerraform color="#7b42bc" />,
  docker: <SiDocker color="#2496ed" />,
  githubactions: <SiGithubactions color="#2088ff" />,
  git: <SiGit color="#f05032" />,
  mongodb: <SiMongodb color="#47a248" />,
  mysql: <SiMysql color="#4479a1" />,
  sqlite: <SiSqlite color="#003b57" />,
  salesforce: <SiSalesforce color="#00a1e0" />,
  magento: <SiMagento color="#ee672f" />,
  wordpress: <SiWordpress color="#21759b" />,
  adobe: <SiAdobe color="#eb1000" />,
  photoshop: <SiAdobephotoshop color="#31a8ff" />,
  adobexd: <SiAdobexd color="#ff61f6" />,
  illustrator: <SiAdobeillustrator color="#ff9a00" />,
};
